{{- if .Values.loki.useBoltDBShipper }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "loki-helm.ingester" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "loki-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingester
    app.kubernetes.io/part-of: memberlist
spec:
  replicas: {{ .Values.ingester.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels: {{- include "loki-helm.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ingester
  serviceName: {{ include "loki-helm.ingester" . }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        config_hash: 8f80031113ab434770ef7e9215512968
      labels: {{- include "loki-helm.labels" . | nindent 8 }}
        app.kubernetes.io/component: ingester
        app.kubernetes.io/part-of: memberlist
    spec:
      {{- if .Values.ingester.affinity }}
      affinity: {{- toYaml .Values.ingester.affinity | nindent 8 }}
      {{- else }}
      affinity: 
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels: {{- include "loki-helm.selectorLabels" . | nindent 16 }}
                app.kubernetes.io/component: ingester
            topologyKey: kubernetes.io/hostname
      {{- end }}
      nodeSelector:
        {{- toYaml .Values.ingester.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.ingester.tolerations | nindent 8 }}
      containers:
      - args:
        - -boltdb.shipper.active-index-directory=/data/index
        - -boltdb.shipper.cache-location=/data/boltdb-cache
        - -config.file=/etc/loki/config/config.yaml
        - -ingester.max-transfer-retries=0
        - -limits.per-user-override-config=/etc/loki/overrides/overrides.yaml
        - -target=ingester
        image: {{ .Values.loki.image }}
        imagePullPolicy: {{ .Values.loki.pullPolicy | quote }}
        name: ingester
        {{- if .Values.ingester.env }}
        env: {{- toYaml .Values.ingester.env | nindent 8 }}
        {{- end }}
        ports:
        - containerPort: 3100
          name: http-metrics
        - containerPort: 9095
          name: grpc
        {{- if .Values.memberlist.enable }}
        - containerPort: {{ .Values.memberlist.port}}
          name: memberlist
        {{- end }}
        readinessProbe:
          httpGet:
            path: /ready
            port: 3100
          initialDelaySeconds: 15
          timeoutSeconds: 1
        {{- if .Values.ingester.resources }}
        resources: {{- toYaml .Values.ingester.resources | nindent 12 }}
        {{- end }}
        volumeMounts:
        - mountPath: /etc/loki/config
          name: loki
        - mountPath: /etc/loki/overrides
          name: overrides
        - mountPath: /data
          name: ingester-data
        {{- with .Values.ingester.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      securityContext:
        fsGroup: 10001
      terminationGracePeriodSeconds: 4800
      volumes:
      - configMap:
          name: {{ include "loki-helm.fullname" . }}-config
        name: loki
      - configMap:
          name: {{ include "loki-helm.fullname" . }}-overrides
        name: overrides
      {{- with .Values.ingester.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: ingester-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.ingester.persistence.size | quote }}
      storageClassName: {{ .Values.ingester.persistence.storageClass }}
{{- end }}