apiVersion: v1
kind: Service
metadata:
  labels: {{- include "loki-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingester
  name: {{ include "loki-helm.ingester" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: ingester-http-metrics
    port: 3100
    targetPort: 3100
  - name: ingester-grpc
    port: 9095
    targetPort: 9095
  selector: {{- include "loki-helm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ingester
