{{ if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "site24x7-exporter.fullname" . }}
  labels:
    {{- include "site24x7-exporter.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - port: http
    {{- if .Values.serviceMonitor.interval }}
    interval: {{ .Values.serviceMonitor.interval }}
    {{- end }}
    {{- if .Values.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    {{- end }}
    {{- with .Values.serviceMonitor.endpoints }}
      {{- toYaml . | nindent 2 }}
    {{- end }}
  selector:
    matchLabels:
      {{- include "site24x7-exporter.selectorLabels" . | nindent 6 }}
{{- end }}
