apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus-statuspage-pusher.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-statuspage-pusher.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "prometheus-statuspage-pusher.selectorLabels" . | nindent 6 }}
  {{- with .Values.strategy }}
  strategy: {{ toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "prometheus-statuspage-pusher.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          args:
            - -c="/etc/statuspage-pusher/queries.yaml"
            - -i={{ .Values.statuspage.pushInterval }}
            - -si={{ .Values.statuspage.id | quote }}
            - -su={{ .Values.statuspage.url | quote }}
            - -pu={{ .Values.prometheus.url | quote }}
        {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.envFrom }}
          envFrom:
          {{- toYaml . | nindent 12 }}
        {{- end }}
          volumeMounts:
            - name: queries
              mountPath: /etc/statuspage-pusher/
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if .Values.serviceMonitor.enabled }}
          ports:
            - name: http
              containerPort: 9095
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: queries
          configMap:
            name: {{ include "prometheus-statuspage-pusher.fullname" . }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
