{{- if eq .Values.loki.useBoltDBShipper false}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki-helm.memcached-index-writes" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "loki-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: memcached-index-writes
spec:
  clusterIP: None
  ports:
  - name: memcached-client
    port: 11211
    targetPort: 11211
  - name: exporter-http-metrics
    port: 9150
    targetPort: 9150
  selector: {{- include "loki-helm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: memcached-index-writes
{{- end }}
