apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "k8s-node-termination-handler.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-node-termination-handler.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "k8s-node-termination-handler.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "k8s-node-termination-handler.selectorLabels" . | nindent 8 }}
    spec:
      hostPID: true
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "k8s-node-termination-handler.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: 
            - "./node-termination-handler"
          args:
            - "--logtostderr"
            - "--exclude-pods=$(POD_NAME):$(POD_NAMESPACE)"
            - "-v=10"
            - "--taint=cloud.google.com/impending-node-termination::NoSchedule"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- with .Values.envFrom }}
          envFrom:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
        {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
    {{- end }}