apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loki-helm.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels: {{- include "loki-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: loki-config
data:
  config.yaml: |
    {{- tpl .Values.loki.config . | nindent 4 }}